import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/lib/components/NavBar";
import { Manrope } from "next/font/google";

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} font-sans antialiased bg-gray-100`}
        style={{
          fontFamily: "'Manrope', system-ui, -apple-system, sans-serif",
          ['--bs-font-monospace' as string]: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
        }}
      >
        <div className=" w-full h-full md:flex ">
          <NavBar />
          <div className="w-full h-full ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
